version: '3.8'

services:
  pg-otus:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: calendar
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  rmq-otus:
    image: rabbitmq:3-management
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    #volumes:
    #  - rabbitmq_data:/var/lib/rabbitmq
  calendar-otus:
    image: calendar:v001
    container_name: calendar
    environment:
      DB_HOST: ${DB_HOST:-172.30.1.126}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "8080:8080"
      - "50051:50051"
#volumes:
#  postgres_data:
#  rabbitmq_data:
