valkey:
  architecture: standalone
  auth:
    enabled: false

ingress-nginx:
  controller:
    service:
      type: LoadBalancer

postgresDb:
  image:
    repository: postgres:17.5
    tag: "17.5"
    version: "17.5"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: postgres-db.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
