postgresDb:
  image:
    repository: postgres:17.5
    tag: "17.5"
    version: "17.5"
  replicaCount: 1
  service:
    type: NodePort
    port: 5432
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: postgres-db.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  env:
    db:
      database: calendar
      user: postgres
      password: password
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1024Mi    
