apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbit-mq.fullname" . }}
  labels:
    {{- include "rabbit-mq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitMq.replicaCount }}
  selector:
    matchLabels:
      {{- include "rabbit-mq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rabbit-mq.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: rabbit-mq
          image: "{{ .Values.rabbitMq.image.repository }}:{{ .Values.rabbitMq.image.tag }}"
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitMq.env.user }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.rabbitMq.env.password }}"
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - rabbitmqctl
                - status
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.rabbitMq.resources | nindent 12 }}
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: {{ include "rabbit-mq.fullname" . }}