apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rabbit-mq.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitMq.persistence.size }}