apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-db.fullname" . }}
spec:
  replicas: {{ .Values.postgresDb.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres-db.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-db.fullname" . }}
    spec:
      containers:
        - name: otus-app
          image: "{{ .Values.postgresDb.image.repository }}:{{ .Values.postgresDb.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "{{ .Values.postgresDb.image.version }}"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
