apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-db.fullname" . }}
spec:
  replicas: {{ .Values.postgresDb.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres-db.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-db.fullname" . }}
    spec:
      containers:
        - name: postgres-db
          image: "{{ .Values.postgresDb.image.repository }}:{{ .Values.postgresDb.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: APP_VERSION
              value: "{{ .Values.postgresDb.image.version }}"
            - name: DB_USER
              value: "{{ .Values.db.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.db.password }}"                
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "psql -h localhost -U postgres -d postgres -c 'SELECT 1;' && exit 0 || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6            