nameOverride: "rabbit-mq"
fullnameOverride: "rabbit-mq"

# Dependencies configurations
valkey:
  enabled: false
  architecture: standalone
  auth:
    enabled: false

ingress-nginx:
  enabled: true
  controller:
    service:
      type: LoadBalancer
    ingressClassResource:
      name: nginx
      enabled: true
      default: true

# RabbitMQ configuration
rabbitMq:
  image:
    repository: rabbitmq
    tag: "3-management"
  replicaCount: 1
  service:
    type: ClusterIP
    amqpPort: 5672
    managementPort: 15672
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: rabbit-mq.local
        paths:
          - path: /
            pathType: Prefix
  env:
    user: "guest"
    password: "guest"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  persistence:
    size: 1Gi