package config

// rest api client
const (
	CALENDAR_REST_API_HOST_ENV     = "CALENDAR_REST_API_HOST"
	CALENDAR_REST_API_HOST_DEFAULT = "localhost"
	CALENDAR_REST_API_PORT_ENV     = "CALENDAR_REST_API_PORT"
	CALENDAR_REST_API_PORT_DEFAULT = "8888"
)
