package config

// rest api client envs
const (
	CALENDAR_REST_API_HOST_ENV     = "CALENDAR_REST_API_HOST"
	CALENDAR_REST_API_HOST_DEFAULT = "localhost"
	CALENDAR_REST_API_PORT_ENV     = "CALENDAR_REST_API_PORT"
	CALENDAR_REST_API_PORT_DEFAULT = "8888"
)

// grpc api client  envs
const (
	CALENDAR_GRPC_API_HOST_ENV     = "CALENDAR_GRPC_API_HOST"
	CALENDAR_GRPC_API_HOST_DEFAULT = "localhost"
	CALENDAR_GRPC_API_PORT_ENV     = "CALENDAR_GRPC_API_PORT"
	CALENDAR_GRPC_API_PORT_DEFAULT = "8888"
)

// repo envs
const (
	CALENDAR_DB_HOST_ENV         = "CALENDAR_DB_HOST"
	CALENDAR_DB_HOST_DEFAULT     = "localhost"
	CALENDAR_DB_PORT_ENV         = "CALENDAR_DB_PORT"
	CALENDAR_DB_PORT_DEFAULT     = "5432"
	CALENDAR_DB_NAME_ENV         = "CALENDAR_DB_NAME"
	CALENDAR_DB_NAME_DEFAULT     = "calendar"
	CALENDAR_DB_USER_ENV         = "CALENDAR_DB_USER"
	CALENDAR_DB_USER_DEFAULT     = "user"
	CALENDAR_DB_PASSWORD_ENV     = "CALENDAR_DB_PASSWORD"
	CALENDAR_DB_PASSWORD_DEFAULT = "password"
)
