// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: calendar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_SUCCESS     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_ERROR       OperationStatus = 2
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_SUCCESS",
		2: "OPERATION_STATUS_ERROR",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_SUCCESS":     1,
		"OPERATION_STATUS_ERROR":       2,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_calendar_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_calendar_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0}
}

type GetEventListPeriod int32

const (
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_UNSPECIFIED GetEventListPeriod = 0
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_DAY         GetEventListPeriod = 1
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_WEEK        GetEventListPeriod = 2
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_MONTH       GetEventListPeriod = 3
)

// Enum value maps for GetEventListPeriod.
var (
	GetEventListPeriod_name = map[int32]string{
		0: "GET_EVENT_LIST_PERIOD_UNSPECIFIED",
		1: "GET_EVENT_LIST_PERIOD_DAY",
		2: "GET_EVENT_LIST_PERIOD_WEEK",
		3: "GET_EVENT_LIST_PERIOD_MONTH",
	}
	GetEventListPeriod_value = map[string]int32{
		"GET_EVENT_LIST_PERIOD_UNSPECIFIED": 0,
		"GET_EVENT_LIST_PERIOD_DAY":         1,
		"GET_EVENT_LIST_PERIOD_WEEK":        2,
		"GET_EVENT_LIST_PERIOD_MONTH":       3,
	}
)

func (x GetEventListPeriod) Enum() *GetEventListPeriod {
	p := new(GetEventListPeriod)
	*p = x
	return p
}

func (x GetEventListPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetEventListPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_calendar_proto_enumTypes[1].Descriptor()
}

func (GetEventListPeriod) Type() protoreflect.EnumType {
	return &file_calendar_proto_enumTypes[1]
}

func (x GetEventListPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetEventListPeriod.Descriptor instead.
func (GetEventListPeriod) EnumDescriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{1}
}

type ServiceName int32

const (
	ServiceName_SERVICE_NAME_UNSPECIFIED ServiceName = 0
	ServiceName_SERVICE_NAME_CALENDAR    ServiceName = 1
)

// Enum value maps for ServiceName.
var (
	ServiceName_name = map[int32]string{
		0: "SERVICE_NAME_UNSPECIFIED",
		1: "SERVICE_NAME_CALENDAR",
	}
	ServiceName_value = map[string]int32{
		"SERVICE_NAME_UNSPECIFIED": 0,
		"SERVICE_NAME_CALENDAR":    1,
	}
)

func (x ServiceName) Enum() *ServiceName {
	p := new(ServiceName)
	*p = x
	return p
}

func (x ServiceName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceName) Descriptor() protoreflect.EnumDescriptor {
	return file_calendar_proto_enumTypes[2].Descriptor()
}

func (ServiceName) Type() protoreflect.EnumType {
	return &file_calendar_proto_enumTypes[2]
}

func (x ServiceName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceName.Descriptor instead.
func (ServiceName) EnumDescriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{2}
}

type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_UNSPECIFIED ResponseStatus = 0
	ResponseStatus_RESPONSE_STATUS_OK          ResponseStatus = 200
	ResponseStatus_RESPONSE_STATUS_BAD_REQUEST ResponseStatus = 400
	ResponseStatus_RESPONSE_STATUS_NOT_FOUND   ResponseStatus = 404
	ResponseStatus_RESPONSE_STATUS_CONFLICT    ResponseStatus = 409
	ResponseStatus_RESPONSE_STATUS_INTERNAL    ResponseStatus = 500
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0:   "RESPONSE_STATUS_UNSPECIFIED",
		200: "RESPONSE_STATUS_OK",
		400: "RESPONSE_STATUS_BAD_REQUEST",
		404: "RESPONSE_STATUS_NOT_FOUND",
		409: "RESPONSE_STATUS_CONFLICT",
		500: "RESPONSE_STATUS_INTERNAL",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_UNSPECIFIED": 0,
		"RESPONSE_STATUS_OK":          200,
		"RESPONSE_STATUS_BAD_REQUEST": 400,
		"RESPONSE_STATUS_NOT_FOUND":   404,
		"RESPONSE_STATUS_CONFLICT":    409,
		"RESPONSE_STATUS_INTERNAL":    500,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_calendar_proto_enumTypes[3].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_calendar_proto_enumTypes[3]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{3}
}

type ProtoEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reminder      *durationpb.Duration   `protobuf:"bytes,7,opt,name=reminder,proto3" json:"reminder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoEvent) Reset() {
	*x = ProtoEvent{}
	mi := &file_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEvent) ProtoMessage() {}

func (x *ProtoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEvent.ProtoReflect.Descriptor instead.
func (*ProtoEvent) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProtoEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProtoEvent) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ProtoEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtoEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProtoEvent) GetReminder() *durationpb.Duration {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type GetEventListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        GetEventListPeriod     `protobuf:"varint,1,opt,name=period,proto3,enum=event.GetEventListPeriod" json:"period,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListRequest) Reset() {
	*x = GetEventListRequest{}
	mi := &file_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListRequest) ProtoMessage() {}

func (x *GetEventListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListRequest.ProtoReflect.Descriptor instead.
func (*GetEventListRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventListRequest) GetPeriod() GetEventListPeriod {
	if x != nil {
		return x.Period
	}
	return GetEventListPeriod_GET_EVENT_LIST_PERIOD_UNSPECIFIED
}

func (x *GetEventListRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type GetEventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=event.OperationStatus" json:"status,omitempty"`
	Events        []*ProtoEvent          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListResponse) Reset() {
	*x = GetEventListResponse{}
	mi := &file_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListResponse) ProtoMessage() {}

func (x *GetEventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListResponse.ProtoReflect.Descriptor instead.
func (*GetEventListResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventListResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetEventListResponse) GetEvents() []*ProtoEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventListResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type AddEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProtoEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventRequest) Reset() {
	*x = AddEventRequest{}
	mi := &file_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventRequest) ProtoMessage() {}

func (x *AddEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventRequest.ProtoReflect.Descriptor instead.
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *AddEventRequest) GetEvent() *ProtoEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type AddEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=event.OperationStatus" json:"status,omitempty"`
	Event         *ProtoEvent            `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventResponse) Reset() {
	*x = AddEventResponse{}
	mi := &file_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventResponse) ProtoMessage() {}

func (x *AddEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventResponse.ProtoReflect.Descriptor instead.
func (*AddEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *AddEventResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *AddEventResponse) GetEvent() *ProtoEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AddEventResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProtoEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetEvent() *ProtoEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=event.OperationStatus" json:"status,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *UpdateEventResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=event.OperationStatus" json:"status,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEventResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *DeleteEventResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   ServiceName            `protobuf:"varint,1,opt,name=service_name,json=serviceName,proto3,enum=event.ServiceName" json:"service_name,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=event.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_calendar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetServiceName() ServiceName {
	if x != nil {
		return x.ServiceName
	}
	return ServiceName_SERVICE_NAME_UNSPECIFIED
}

func (x *Error) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Error) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_calendar_proto protoreflect.FileDescriptor

const file_calendar_proto_rawDesc = "" +
	"\n" +
	"\x0ecalendar.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x96\x02\n" +
	"\n" +
	"ProtoEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x125\n" +
	"\breminder\x18\a \x01(\v2\x19.google.protobuf.DurationR\breminder\"\x83\x01\n" +
	"\x13GetEventListRequest\x121\n" +
	"\x06period\x18\x01 \x01(\x0e2\x19.event.GetEventListPeriodR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\x95\x01\n" +
	"\x14GetEventListResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.event.OperationStatusR\x06status\x12)\n" +
	"\x06events\x18\x02 \x03(\v2\x11.event.ProtoEventR\x06events\x12\"\n" +
	"\x05error\x18\x03 \x01(\v2\f.event.ErrorR\x05error\":\n" +
	"\x0fAddEventRequest\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.event.ProtoEventR\x05event\"\x8f\x01\n" +
	"\x10AddEventResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.event.OperationStatusR\x06status\x12'\n" +
	"\x05event\x18\x02 \x01(\v2\x11.event.ProtoEventR\x05event\x12\"\n" +
	"\x05error\x18\x03 \x01(\v2\f.event.ErrorR\x05error\"=\n" +
	"\x12UpdateEventRequest\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.event.ProtoEventR\x05event\"i\n" +
	"\x13UpdateEventResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.event.OperationStatusR\x06status\x12\"\n" +
	"\x05error\x18\x02 \x01(\v2\f.event.ErrorR\x05error\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x13DeleteEventResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.event.OperationStatusR\x06status\x12\"\n" +
	"\x05error\x18\x02 \x01(\v2\f.event.ErrorR\x05error\"\xe0\x01\n" +
	"\x05Error\x125\n" +
	"\fservice_name\x18\x01 \x01(\x0e2\x12.event.ServiceNameR\vserviceName\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.event.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*m\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_SUCCESS\x10\x01\x12\x1a\n" +
	"\x16OPERATION_STATUS_ERROR\x10\x02*\x9b\x01\n" +
	"\x12GetEventListPeriod\x12%\n" +
	"!GET_EVENT_LIST_PERIOD_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GET_EVENT_LIST_PERIOD_DAY\x10\x01\x12\x1e\n" +
	"\x1aGET_EVENT_LIST_PERIOD_WEEK\x10\x02\x12\x1f\n" +
	"\x1bGET_EVENT_LIST_PERIOD_MONTH\x10\x03*F\n" +
	"\vServiceName\x12\x1c\n" +
	"\x18SERVICE_NAME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SERVICE_NAME_CALENDAR\x10\x01*\xca\x01\n" +
	"\x0eResponseStatus\x12\x1f\n" +
	"\x1bRESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x12RESPONSE_STATUS_OK\x10\xc8\x01\x12 \n" +
	"\x1bRESPONSE_STATUS_BAD_REQUEST\x10\x90\x03\x12\x1e\n" +
	"\x19RESPONSE_STATUS_NOT_FOUND\x10\x94\x03\x12\x1d\n" +
	"\x18RESPONSE_STATUS_CONFLICT\x10\x99\x03\x12\x1d\n" +
	"\x18RESPONSE_STATUS_INTERNAL\x10\xf4\x032\x98\x02\n" +
	"\bCalendar\x12C\n" +
	"\bGetEvent\x12\x1a.event.GetEventListRequest\x1a\x1b.event.GetEventListResponse\x12;\n" +
	"\bAddEvent\x12\x16.event.AddEventRequest\x1a\x17.event.AddEventResponse\x12D\n" +
	"\vUpdateEvent\x12\x19.event.UpdateEventRequest\x1a\x1a.event.UpdateEventResponse\x12D\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\x1a.event.DeleteEventResponseB\x1bZ\x19./internal/server/grpc/pbb\x06proto3"

var (
	file_calendar_proto_rawDescOnce sync.Once
	file_calendar_proto_rawDescData []byte
)

func file_calendar_proto_rawDescGZIP() []byte {
	file_calendar_proto_rawDescOnce.Do(func() {
		file_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)))
	})
	return file_calendar_proto_rawDescData
}

var file_calendar_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_calendar_proto_goTypes = []any{
	(OperationStatus)(0),          // 0: event.OperationStatus
	(GetEventListPeriod)(0),       // 1: event.GetEventListPeriod
	(ServiceName)(0),              // 2: event.ServiceName
	(ResponseStatus)(0),           // 3: event.ResponseStatus
	(*ProtoEvent)(nil),            // 4: event.ProtoEvent
	(*GetEventListRequest)(nil),   // 5: event.GetEventListRequest
	(*GetEventListResponse)(nil),  // 6: event.GetEventListResponse
	(*AddEventRequest)(nil),       // 7: event.AddEventRequest
	(*AddEventResponse)(nil),      // 8: event.AddEventResponse
	(*UpdateEventRequest)(nil),    // 9: event.UpdateEventRequest
	(*UpdateEventResponse)(nil),   // 10: event.UpdateEventResponse
	(*DeleteEventRequest)(nil),    // 11: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),   // 12: event.DeleteEventResponse
	(*Error)(nil),                 // 13: event.Error
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 15: google.protobuf.Duration
}
var file_calendar_proto_depIdxs = []int32{
	14, // 0: event.ProtoEvent.start_time:type_name -> google.protobuf.Timestamp
	15, // 1: event.ProtoEvent.duration:type_name -> google.protobuf.Duration
	15, // 2: event.ProtoEvent.reminder:type_name -> google.protobuf.Duration
	1,  // 3: event.GetEventListRequest.period:type_name -> event.GetEventListPeriod
	14, // 4: event.GetEventListRequest.start_time:type_name -> google.protobuf.Timestamp
	0,  // 5: event.GetEventListResponse.status:type_name -> event.OperationStatus
	4,  // 6: event.GetEventListResponse.events:type_name -> event.ProtoEvent
	13, // 7: event.GetEventListResponse.error:type_name -> event.Error
	4,  // 8: event.AddEventRequest.event:type_name -> event.ProtoEvent
	0,  // 9: event.AddEventResponse.status:type_name -> event.OperationStatus
	4,  // 10: event.AddEventResponse.event:type_name -> event.ProtoEvent
	13, // 11: event.AddEventResponse.error:type_name -> event.Error
	4,  // 12: event.UpdateEventRequest.event:type_name -> event.ProtoEvent
	0,  // 13: event.UpdateEventResponse.status:type_name -> event.OperationStatus
	13, // 14: event.UpdateEventResponse.error:type_name -> event.Error
	0,  // 15: event.DeleteEventResponse.status:type_name -> event.OperationStatus
	13, // 16: event.DeleteEventResponse.error:type_name -> event.Error
	2,  // 17: event.Error.service_name:type_name -> event.ServiceName
	3,  // 18: event.Error.status:type_name -> event.ResponseStatus
	14, // 19: event.Error.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 20: event.Calendar.GetEvent:input_type -> event.GetEventListRequest
	7,  // 21: event.Calendar.AddEvent:input_type -> event.AddEventRequest
	9,  // 22: event.Calendar.UpdateEvent:input_type -> event.UpdateEventRequest
	11, // 23: event.Calendar.DeleteEvent:input_type -> event.DeleteEventRequest
	6,  // 24: event.Calendar.GetEvent:output_type -> event.GetEventListResponse
	8,  // 25: event.Calendar.AddEvent:output_type -> event.AddEventResponse
	10, // 26: event.Calendar.UpdateEvent:output_type -> event.UpdateEventResponse
	12, // 27: event.Calendar.DeleteEvent:output_type -> event.DeleteEventResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_calendar_proto_init() }
func file_calendar_proto_init() {
	if File_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calendar_proto_goTypes,
		DependencyIndexes: file_calendar_proto_depIdxs,
		EnumInfos:         file_calendar_proto_enumTypes,
		MessageInfos:      file_calendar_proto_msgTypes,
	}.Build()
	File_calendar_proto = out.File
	file_calendar_proto_goTypes = nil
	file_calendar_proto_depIdxs = nil
}
