apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calendar.fullname" . }}
spec:
  replicas: {{ .Values.calendar.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "calendar.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "calendar.fullname" . }}
    spec:
      containers:
        - name: calendar
          image: "{{ .Values.calendar.image.repository }}:{{ .Values.calendar.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: DB_HOST
              value: "{{ .Values.calendar.env.db.host }}"
            - name: DB_USER
              value: "{{ .Values.calendar.env.db.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.calendar.env.db.password }}"                 
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 30
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3  
          resources:
            {{- toYaml .Values.calendar.resources }}          
