apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendar.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "calendar.selectorLabels" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
