// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: calendar.proto

// protoc --proto_path=./api --go_out=./internal/server/grpc/pb --go-grpc_out=./internal/server/grpc/pb ./api/calendar.proto
// protoc --proto_path=./api --go_out=./test/integration/client/grpc/pb --go-grpc_out=./test/integration/client/grpc/pb ./api/calendar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventListPeriod int32

const (
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_UNSPECIFIED GetEventListPeriod = 0
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_DAY         GetEventListPeriod = 1
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_WEEK        GetEventListPeriod = 2
	GetEventListPeriod_GET_EVENT_LIST_PERIOD_MONTH       GetEventListPeriod = 3
)

// Enum value maps for GetEventListPeriod.
var (
	GetEventListPeriod_name = map[int32]string{
		0: "GET_EVENT_LIST_PERIOD_UNSPECIFIED",
		1: "GET_EVENT_LIST_PERIOD_DAY",
		2: "GET_EVENT_LIST_PERIOD_WEEK",
		3: "GET_EVENT_LIST_PERIOD_MONTH",
	}
	GetEventListPeriod_value = map[string]int32{
		"GET_EVENT_LIST_PERIOD_UNSPECIFIED": 0,
		"GET_EVENT_LIST_PERIOD_DAY":         1,
		"GET_EVENT_LIST_PERIOD_WEEK":        2,
		"GET_EVENT_LIST_PERIOD_MONTH":       3,
	}
)

func (x GetEventListPeriod) Enum() *GetEventListPeriod {
	p := new(GetEventListPeriod)
	*p = x
	return p
}

func (x GetEventListPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetEventListPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_calendar_proto_enumTypes[0].Descriptor()
}

func (GetEventListPeriod) Type() protoreflect.EnumType {
	return &file_calendar_proto_enumTypes[0]
}

func (x GetEventListPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetEventListPeriod.Descriptor instead.
func (GetEventListPeriod) EnumDescriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0}
}

type ProtoEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reminder      *durationpb.Duration   `protobuf:"bytes,7,opt,name=reminder,proto3" json:"reminder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoEvent) Reset() {
	*x = ProtoEvent{}
	mi := &file_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEvent) ProtoMessage() {}

func (x *ProtoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEvent.ProtoReflect.Descriptor instead.
func (*ProtoEvent) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProtoEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProtoEvent) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ProtoEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtoEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProtoEvent) GetReminder() *durationpb.Duration {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type GetEventListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        GetEventListPeriod     `protobuf:"varint,1,opt,name=period,proto3,enum=event.GetEventListPeriod" json:"period,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListRequest) Reset() {
	*x = GetEventListRequest{}
	mi := &file_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListRequest) ProtoMessage() {}

func (x *GetEventListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListRequest.ProtoReflect.Descriptor instead.
func (*GetEventListRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventListRequest) GetPeriod() GetEventListPeriod {
	if x != nil {
		return x.Period
	}
	return GetEventListPeriod_GET_EVENT_LIST_PERIOD_UNSPECIFIED
}

func (x *GetEventListRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type GetEventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ProtoEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListResponse) Reset() {
	*x = GetEventListResponse{}
	mi := &file_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListResponse) ProtoMessage() {}

func (x *GetEventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListResponse.ProtoReflect.Descriptor instead.
func (*GetEventListResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventListResponse) GetEvents() []*ProtoEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AddEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProtoEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventRequest) Reset() {
	*x = AddEventRequest{}
	mi := &file_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventRequest) ProtoMessage() {}

func (x *AddEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventRequest.ProtoReflect.Descriptor instead.
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *AddEventRequest) GetEvent() *ProtoEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type AddEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProtoEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventResponse) Reset() {
	*x = AddEventResponse{}
	mi := &file_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventResponse) ProtoMessage() {}

func (x *AddEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventResponse.ProtoReflect.Descriptor instead.
func (*AddEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *AddEventResponse) GetEvent() *ProtoEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProtoEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetEvent() *ProtoEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{6}
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_proto_rawDescGZIP(), []int{8}
}

var File_calendar_proto protoreflect.FileDescriptor

const file_calendar_proto_rawDesc = "" +
	"\n" +
	"\x0ecalendar.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x96\x02\n" +
	"\n" +
	"ProtoEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x125\n" +
	"\breminder\x18\a \x01(\v2\x19.google.protobuf.DurationR\breminder\"\x83\x01\n" +
	"\x13GetEventListRequest\x121\n" +
	"\x06period\x18\x01 \x01(\x0e2\x19.event.GetEventListPeriodR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"A\n" +
	"\x14GetEventListResponse\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.event.ProtoEventR\x06events\":\n" +
	"\x0fAddEventRequest\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.event.ProtoEventR\x05event\";\n" +
	"\x10AddEventResponse\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.event.ProtoEventR\x05event\"=\n" +
	"\x12UpdateEventRequest\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.event.ProtoEventR\x05event\"\x15\n" +
	"\x13UpdateEventResponse\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEventResponse*\x9b\x01\n" +
	"\x12GetEventListPeriod\x12%\n" +
	"!GET_EVENT_LIST_PERIOD_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GET_EVENT_LIST_PERIOD_DAY\x10\x01\x12\x1e\n" +
	"\x1aGET_EVENT_LIST_PERIOD_WEEK\x10\x02\x12\x1f\n" +
	"\x1bGET_EVENT_LIST_PERIOD_MONTH\x10\x032\x98\x02\n" +
	"\bCalendar\x12C\n" +
	"\bGetEvent\x12\x1a.event.GetEventListRequest\x1a\x1b.event.GetEventListResponse\x12;\n" +
	"\bAddEvent\x12\x16.event.AddEventRequest\x1a\x17.event.AddEventResponse\x12D\n" +
	"\vUpdateEvent\x12\x19.event.UpdateEventRequest\x1a\x1a.event.UpdateEventResponse\x12D\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\x1a.event.DeleteEventResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_calendar_proto_rawDescOnce sync.Once
	file_calendar_proto_rawDescData []byte
)

func file_calendar_proto_rawDescGZIP() []byte {
	file_calendar_proto_rawDescOnce.Do(func() {
		file_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)))
	})
	return file_calendar_proto_rawDescData
}

var file_calendar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_calendar_proto_goTypes = []any{
	(GetEventListPeriod)(0),       // 0: event.GetEventListPeriod
	(*ProtoEvent)(nil),            // 1: event.ProtoEvent
	(*GetEventListRequest)(nil),   // 2: event.GetEventListRequest
	(*GetEventListResponse)(nil),  // 3: event.GetEventListResponse
	(*AddEventRequest)(nil),       // 4: event.AddEventRequest
	(*AddEventResponse)(nil),      // 5: event.AddEventResponse
	(*UpdateEventRequest)(nil),    // 6: event.UpdateEventRequest
	(*UpdateEventResponse)(nil),   // 7: event.UpdateEventResponse
	(*DeleteEventRequest)(nil),    // 8: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),   // 9: event.DeleteEventResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 11: google.protobuf.Duration
}
var file_calendar_proto_depIdxs = []int32{
	10, // 0: event.ProtoEvent.start_time:type_name -> google.protobuf.Timestamp
	11, // 1: event.ProtoEvent.duration:type_name -> google.protobuf.Duration
	11, // 2: event.ProtoEvent.reminder:type_name -> google.protobuf.Duration
	0,  // 3: event.GetEventListRequest.period:type_name -> event.GetEventListPeriod
	10, // 4: event.GetEventListRequest.start_time:type_name -> google.protobuf.Timestamp
	1,  // 5: event.GetEventListResponse.events:type_name -> event.ProtoEvent
	1,  // 6: event.AddEventRequest.event:type_name -> event.ProtoEvent
	1,  // 7: event.AddEventResponse.event:type_name -> event.ProtoEvent
	1,  // 8: event.UpdateEventRequest.event:type_name -> event.ProtoEvent
	2,  // 9: event.Calendar.GetEvent:input_type -> event.GetEventListRequest
	4,  // 10: event.Calendar.AddEvent:input_type -> event.AddEventRequest
	6,  // 11: event.Calendar.UpdateEvent:input_type -> event.UpdateEventRequest
	8,  // 12: event.Calendar.DeleteEvent:input_type -> event.DeleteEventRequest
	3,  // 13: event.Calendar.GetEvent:output_type -> event.GetEventListResponse
	5,  // 14: event.Calendar.AddEvent:output_type -> event.AddEventResponse
	7,  // 15: event.Calendar.UpdateEvent:output_type -> event.UpdateEventResponse
	9,  // 16: event.Calendar.DeleteEvent:output_type -> event.DeleteEventResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_calendar_proto_init() }
func file_calendar_proto_init() {
	if File_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_proto_rawDesc), len(file_calendar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calendar_proto_goTypes,
		DependencyIndexes: file_calendar_proto_depIdxs,
		EnumInfos:         file_calendar_proto_enumTypes,
		MessageInfos:      file_calendar_proto_msgTypes,
	}.Build()
	File_calendar_proto = out.File
	file_calendar_proto_goTypes = nil
	file_calendar_proto_depIdxs = nil
}
