logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: COLOUR_TEXT

storage:
  # IN_MEMORY, SQL
  type: IN_MEMORY

http:
  server:
    host: localhost
    port: 8080
    path:
      hello: /hello 
