logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: COLOUR_TEXT

storage:
  # IN_MEMORY, SQL
  type: SQL
  psql:
    dsn: host=localhost port=5432 user=otus_user password=otus_password dbname=calendar sslmode=disable
    migration: ./migrations
    pool:
      conn:
        max_open: 10
        max_idle: 2
        max_life_time: 3600
        max_idle_time: 3600


http:
  server:
    host: localhost
    port: 8080
    path:
      hello: /hello 
