logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON

storage:
  # IN_MEMORY, SQL
  type: IN_MEMORY
  load_test_data: true # генерация и загрузка тестовых событий в хранилище при старте
  sql:
    db:
      host: localhost
      port: 5432
      name: calendar
      user: ${DB_USER:=user}
      password: ${DB_PASSWORD:=password}
      sslmode: disable
    migration:
      path: ./migrations
      applying: true
    pool:
      conn:
        max_open: 10
        max_idle: 2
        max_life_time: 3600
        max_idle_time: 3600

http:
  server:
    host: localhost
    port: 8080
    path:
      hello: /hello 
