logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON

storage:
  # IN_MEMORY, SQL
  type: SQL
  inMemory:
    loadTestData: true # генерация и загрузка тестовых событий в in-memory хранилище при старте
  sql:
    startParam:
      reconnectAttempt: 5 
      reconnectTimeout: 10 # second
    db:
      host: ${DB_HOST:=localhost}
      port: 5432
      name: calendar
      user: ${DB_USER:=user}
      password: ${DB_PASSWORD:=password}
      sslmode: disable
    pool:
      conn:
        maxOpen: 10
        maxIdle: 2
        maxLifeTime: 3600
        maxIdleTime: 3600
    migration:
      enable: true
      path: ./migrations

http:
  server:
    host: 
    port: 8080
    readHeaderTimeout: 5
    readTimeout: 10
    writeTimeout: 30
    idleTimeout: 90

grpc:
  server:
    network: tcp
    host: localhost
    port: 50051