logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON

storage:
  # IN_MEMORY, SQL
  type: SQL
  psql:
    db:
      host: localhost
      port: 5432
      name: calendar
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      sslmode: disable
    migration: ./migrations
    pool:
      conn:
        max_open: 10
        max_idle: 2
        max_life_time: 3600
        max_idle_time: 3600

http:
  server:
    host: localhost
    port: 8080
    path:
      hello: /hello 
