scheduller:
  cleanup_interval: 86400 # second
  notificate_scan_interval: 30 # second

rmq:
  host: localhost
  port: 5672
  user: ${RMQ_USER:=guest}
  password: ${RMQ_PASSWORD:=guest}
  queue: calendar_notifications  

logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON

storage:
  sql:
    db:
      host: localhost
      port: 5432
      name: calendar
      user: ${DB_USER:=user}
      password: ${DB_PASSWORD:=password}
      sslmode: disable
    pool:
      conn:
        maxOpen: 10
        maxIdle: 2
        maxLifeTime: 3600
        maxIdleTime: 3600