scheduler:
  interval:
    cleanup: 10 # second
    notificate: 10 # second
  processTimeout: 5 # second

rmq:
  #host: ${RMQ_HOST:=localhost}
  host: ${RMQ_HOST:=172.30.1.126}
  port: 5672
  user: ${RMQ_USER:=guest}
  password: ${RMQ_PASSWORD:=guest}
  exchangeName: calendar-exchange
  exchangeType: direct
  queueName: calendar-notifications
  routingKey: calendar-key

logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON

storage:
  sql:
    db:
      #host: ${DB_HOST:=localhost}
      host: ${DB_HOST:=172.30.1.126}
      port: 5432
      name: calendar
      user: ${DB_USER:=user}
      password: ${DB_PASSWORD:=password}
      sslmode: disable
    pool:
      conn:
        maxOpen: 10
        maxIdle: 2
        maxLifeTime: 3600
        maxIdleTime: 3600