rmq:
  host: localhost
  port: 5672
  user: ${RMQ_USER:=guest}
  password: ${RMQ_PASSWORD:=guest}
  exchange_name: calendar-exchange
  exchange_type: direct
  queue_name: calendar-notifications
  routing_key: calendar-key
  consumer_tag: calendar-consumer

logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON