sender:
  interval:
    cleanup: 10 # second
    notificate: 10 # second

rmq:
  host: localhost
  port: 5672
  user: ${RMQ_USER:=guest}
  password: ${RMQ_PASSWORD:=guest}
  exchange_name: calendar-exchange
  exchange_type: direct
  queue_name: calendar-notifications
  routing_key: calendar-key

logger:
  # DEBUG, INFO, WARN, ERROR
  level: INFO 
  # JSON, TEXT, COLOUR_TEXT 
  format: JSON